export const NAV_TYPES = {
  MOBILE_MENU: "MOBILE_MENU",
  DIALOGUE_MENU: 'DIALOGUE_MENU',
  SECONDARY_DIALOGUE_MENU: 'SECONDARY_DIALOGUE_MENU',
  UPLOADING: 'UPLOADING',
  UPTYPE: 'UPTYPE',
  UPPERCENT: 'UPPERCENT',
  UPCATAGORY: 'UPCATAGORY',
};
